### ISSUE TITLE
README needs update

### ISSUE THREAD

**Issue by JiniHendrix** [trodi/electron-splashscreen#11]
in the example in the README one of the fields is splashScreenOptions when it should be splashScreenOpts, it's causing errors if it's set as splashScreenOptions

**Comment by trodi** [comment]
Thanks @JiniHendrix. I've updated the readme example code.

Please also checkout the [real code examples](https://github.com/trodi/electron-splashscreen/tree/master/examples) and the [API](https://github.com/trodi/electron-splashscreen/api-doc/README.md) if necessary.
