### ISSUE TITLE
Transparent Option Not Working

### ISSUE THREAD

**Issue by raquila** [trodi/electron-splashscreen#12]
The transparent option doesn't seem to work in windows 7.  I'm using a separate html page to show a png image.  This does work in windows 10.

**Comment by trodi** [comment]
I just tested on a windows 7 VM without issue. This is likely an issue with your windows 7 settings as noted in electron's documentation:
> On Windows operating systems, transparent windows will not work when DWM is disabled.

See https://github.com/trodi/electron-splashscreen/issues/10#issuecomment-377092200 for more detailed discussion:  
> This issue is likely not an issue with this module. It isn't doing anything special for transparency, all the options are just given to electron to do the heavy lifting. For reference, transparent windows have [limitations](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#limitations).
