### ISSUE TITLE
JavaScript implementation

### ISSUE THREAD

**Issue by TechStudent11** [trodi/electron-splashscreen#28]
I tried to convert the code example in the README to JavaScript, but I cannot figure it out. Can someone please show me a JavaScript implementation?

**Comment by trodi** [comment]
@TechStudent11, I can't be sure what issue you are running in to. Typescript is just a superset of Javascript. Your Javascript will ultimately depend on the Javascript engine you are running on. The two main pieces are to remove all the type annotations and handle the imports correctly. Depending on the JS engine, you'll have access to different set of features.

You can look at the Javascript generated from the Typescript transpilation done on the example uses I provide. Here is a JS translation of the example Typescript.

```Javascript
// import the module
var Splashscreen = require("@trodi/electron-splashscreen");
const mainOpts = <... insert your options ...>
// configure the splashscreen
var config = {
    windowOpts: mainOpts;
    templateUrl: `${__dirname}/splash-screen.html`;
    splashScreenOpts: {
        width: 425,
        height: 325,
    },
};
// initialize the splashscreen handling
const main = Splashscreen.initSplashScreen(config);
// load your browser window per usual
main.loadURL(`file://index.html`);
```

**Comment by TechStudent11** [comment]
@trodi thanks!
