### ISSUE TITLE
1.0.0 - Release

### ISSUE THREAD

**Issue by trodi** [trodi/electron-splashscreen#7]
_This is a place that additional changes can be discussed before a 1.0.0 release happens. **Please comment if you see something missing in this module!**_

I opened this as a place for a chance for those who use this module to comment on API breaking changes as well and general needs, before I publish a 1.0.0 version 🙈.

Possible items:
- [x] Project icon (Add to readme and to the examples)
- [ ] ~~Make supported electron versions known via peer dependency~~
- Any doc improvements?
  - [x] updated doc generator and typescript
- Improvements to improve [npms.io](https://npms.io/) score?
  - [x] releasing 1.0

**Comment by connollykeyjoint** [comment]
Callback/promise after the splash screen is dismissed and main browser window's shown?

**Comment by trodi** [comment]
I've released v1.0.0 🎉
